<?php

namespace app\admin\controller;



/**
 * 栏目管理
 * Class Category
 * @package app\admin\controller
 */
class Category extends Common
{
	protected $db;
	protected function _initialize ()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub
		$this->db = new \app\common\model\Category();
	}

	//首页
    public function index()
	{
		//获取栏目数据
		// $field = db('cate')->select();
		$field = $this->db->getAll();
		// halt($field);
		$this->assign('field',$field);
		return $this->fetch();
	}
	//添加
	public function store()
	{
		if(request()->isPost())
		{
			// halt(input('post.'));
			$res = $this->db->store(input('post.'));
			if($res['valid'])
			{
				//操作成功
				$this->success($res['msg'],'index');exit;
			}else{
				$this->error($res['msg']);exit;
			}
		}
		return $this->fetch();
	}
	public function addSon()
	{
		if(request()->isPost())
		{
			// halt(input('post.'));
			$res = $this->db->store(input('post.'));
			// halt($res);
			if($res['valid'])
			{
				//操作成功
				$this->success($res['msg'],'index');exit;
			}else{
				$this->error($res['msg']);exit;
			}
		}
		$cate_id = input('param.cate_id');
		$data = $this->db->where('cate_id',$cate_id)->find();
		$this->assign('data',$data);
		return $this->fetch();
	}
	public function edit()
	{
		if (request()->isPost()) {
			$res = $this->db->edit(input('post.'));
			if ($res['valid']) {
				$this->success($res['msg'],'index');exit;
			}else{
				$this->error($res['msg']);exit;
			}
		}
		//接受cate_id
		$cate_id = input('param.cate_id');
		// halt($cate_id);
		//接受旧数据
		$oldData = $this->db->find($cate_id);
		$this->assign('oldData',$oldData);
		// halt(db('cate')->select());
		$cateData = $this->db->getCateData($cate_id);
		// halt($cateData);
		$this->assign('cateData',$cateData);
		return $this->fetch();
	}
	/**
	 *删除栏目
	 */
	public function del()
	{
		// $cate_id = input('get.cate_id');
		$res = $this->db->del(input('get.cate_id'));
		if($res['valid'])
		{
			$this->success($res['msg'],'index');exit;
		}else{
			$this->error($res['msg']);exit;
		}
	}
}
